# Generated by Django 4.1 on 2022-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_ingredientitem_type_alter_ingredientitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="description",
            field=models.TextField(default="To change your bio, edit your profile!"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(default="To change your bio, edit your profile!"),
        ),
    ]
